### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by borski**
* Additional variants for Dream Edition, etc.
* Added wakeup functionality
* Added ability to honk horn

### CODE REVIEW

**Comment by borski** [comment]
Also happy to help maintain as you build it out if it gets any traction; I'm excited to build this out.

**Comment by nshp** [comment]
Nice! At this rate we’ll be feature complete by morning, hah. Are you just guessing at these API paths, or did you manage to leak something sensible out of one of the apps?

**Comment by borski** [comment]
> Nice! At this rate we’ll be feature complete by morning, hah. Are you just guessing at these API paths, or did you manage to leak something sensible out of one of the apps?

lol, completely guessing. the paths don't seem to have any semantic meaning, because of course they don't 🙄

Sure would be great if they'd do something sane like /user/1/vehicles/1/wake_up but nooooooooo

**Comment by nshp** [comment]
> I tried packet sniffing my iPhone to grab traffic, but I haven't succeeded; need to find an Android device on which it's less painful
Same here. The Android app is indeed Flutter, so it’s not going to be easy there either. I think on both platforms the majority of Lucid’s traffic does not respect proxy settings, so capturing with mitmproxy or the like doesn’t work. I think what little I managed to capture came from the iOS widget doing its own thing rather than the app itself.

**Comment by borski** [comment]
> I think what little I managed to capture came from the iOS widget doing its own thing rather than the app itself.

Ooh, you sneaky devil. Wish I'd thought of that

**Pull request merged**
